FROM python:3.10-slim

WORKDIR /app

COPY AlertNotifier/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY AlertNotifier/alert_notifier_system.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "alert_notifier_system.py"]