FROM python:3.10-slim

WORKDIR /app

COPY DataCollector/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY DataCollector/data_collector.py .
COPY CircuitBreaker/circuit_breaker.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "data_collector.py"]