# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance_app.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'finance_app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66inance_app.proto\"R\n\nDatiUtente\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x12\n\nhigh_value\x18\x03 \x01(\x02\x12\x11\n\tlow_value\x18\x04 \x01(\x02\"\x16\n\x05\x45mail\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"/\n\x08\x43onferma\x12\x10\n\x08\x63onferma\x18\x01 \x01(\x08\x12\x11\n\tmessaggio\x18\x02 \x01(\t\"\x18\n\x06Valore\x12\x0e\n\x06valore\x18\x01 \x01(\x02\"4\n\x0f\x44\x61tiMediaValori\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nnumeroDati\x18\x02 \x01(\x05\x32\x8f\x01\n\x0eServizioUtente\x12*\n\x0eRegistraUtente\x12\x0b.DatiUtente\x1a\t.Conferma\"\x00\x12*\n\x0e\x41ggiornaUtente\x12\x0b.DatiUtente\x1a\t.Conferma\"\x00\x12%\n\x0e\x43\x61ncellaUtente\x12\x06.Email\x1a\t.Conferma\"\x00\x32g\n\rServizioStock\x12#\n\x0eRecuperaValore\x12\x06.Email\x1a\x07.Valore\"\x00\x12\x31\n\x12\x43\x61lcolaMediaValori\x12\x10.DatiMediaValori\x1a\x07.Valore\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finance_app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATIUTENTE']._serialized_start=21
  _globals['_DATIUTENTE']._serialized_end=103
  _globals['_EMAIL']._serialized_start=105
  _globals['_EMAIL']._serialized_end=127
  _globals['_CONFERMA']._serialized_start=129
  _globals['_CONFERMA']._serialized_end=176
  _globals['_VALORE']._serialized_start=178
  _globals['_VALORE']._serialized_end=202
  _globals['_DATIMEDIAVALORI']._serialized_start=204
  _globals['_DATIMEDIAVALORI']._serialized_end=256
  _globals['_SERVIZIOUTENTE']._serialized_start=259
  _globals['_SERVIZIOUTENTE']._serialized_end=402
  _globals['_SERVIZIOSTOCK']._serialized_start=404
  _globals['_SERVIZIOSTOCK']._serialized_end=507
# @@protoc_insertion_point(module_scope)
