# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import finance_app_pb2 as finance__app__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in finance_app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServizioUtenteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistraUtente = channel.unary_unary(
                '/ServizioUtente/RegistraUtente',
                request_serializer=finance__app__pb2.DatiUtente.SerializeToString,
                response_deserializer=finance__app__pb2.Conferma.FromString,
                _registered_method=True)
        self.AggiornaUtente = channel.unary_unary(
                '/ServizioUtente/AggiornaUtente',
                request_serializer=finance__app__pb2.DatiUtente.SerializeToString,
                response_deserializer=finance__app__pb2.Conferma.FromString,
                _registered_method=True)
        self.CancellaUtente = channel.unary_unary(
                '/ServizioUtente/CancellaUtente',
                request_serializer=finance__app__pb2.Email.SerializeToString,
                response_deserializer=finance__app__pb2.Conferma.FromString,
                _registered_method=True)


class ServizioUtenteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistraUtente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggiornaUtente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancellaUtente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServizioUtenteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistraUtente': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistraUtente,
                    request_deserializer=finance__app__pb2.DatiUtente.FromString,
                    response_serializer=finance__app__pb2.Conferma.SerializeToString,
            ),
            'AggiornaUtente': grpc.unary_unary_rpc_method_handler(
                    servicer.AggiornaUtente,
                    request_deserializer=finance__app__pb2.DatiUtente.FromString,
                    response_serializer=finance__app__pb2.Conferma.SerializeToString,
            ),
            'CancellaUtente': grpc.unary_unary_rpc_method_handler(
                    servicer.CancellaUtente,
                    request_deserializer=finance__app__pb2.Email.FromString,
                    response_serializer=finance__app__pb2.Conferma.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServizioUtente', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServizioUtente', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServizioUtente(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistraUtente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServizioUtente/RegistraUtente',
            finance__app__pb2.DatiUtente.SerializeToString,
            finance__app__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggiornaUtente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServizioUtente/AggiornaUtente',
            finance__app__pb2.DatiUtente.SerializeToString,
            finance__app__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancellaUtente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServizioUtente/CancellaUtente',
            finance__app__pb2.Email.SerializeToString,
            finance__app__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServizioStockStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecuperaValore = channel.unary_unary(
                '/ServizioStock/RecuperaValore',
                request_serializer=finance__app__pb2.Email.SerializeToString,
                response_deserializer=finance__app__pb2.Valore.FromString,
                _registered_method=True)
        self.CalcolaMediaValori = channel.unary_unary(
                '/ServizioStock/CalcolaMediaValori',
                request_serializer=finance__app__pb2.DatiMediaValori.SerializeToString,
                response_deserializer=finance__app__pb2.Valore.FromString,
                _registered_method=True)


class ServizioStockServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecuperaValore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcolaMediaValori(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServizioStockServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecuperaValore': grpc.unary_unary_rpc_method_handler(
                    servicer.RecuperaValore,
                    request_deserializer=finance__app__pb2.Email.FromString,
                    response_serializer=finance__app__pb2.Valore.SerializeToString,
            ),
            'CalcolaMediaValori': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcolaMediaValori,
                    request_deserializer=finance__app__pb2.DatiMediaValori.FromString,
                    response_serializer=finance__app__pb2.Valore.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServizioStock', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServizioStock', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServizioStock(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecuperaValore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServizioStock/RecuperaValore',
            finance__app__pb2.Email.SerializeToString,
            finance__app__pb2.Valore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcolaMediaValori(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServizioStock/CalcolaMediaValori',
            finance__app__pb2.DatiMediaValori.SerializeToString,
            finance__app__pb2.Valore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
